### PR TITLE
Azure cloud provider + Openstack NodeDeployments + Project users

### PR DESCRIPTION
**Pull request by furkhat**

### CODE REVIEW

**Comment by zreigz** [comment]
Please fix compilation error:
```
kubermatic/resource_node_deployment.go:239:66: undefined: nID
kubermatic/resource_node_deployment.go:256:91: undefined: nID

```

**Comment by zreigz** [comment]
@furkhat azure works fine :+1:

**Comment by zreigz** [comment]
@furkhat I had to specify OpenStack credentials manually. Is there any reason why we can't use predefined credentials?

**Comment by zreigz** [comment]
Rest things look good

**Comment by furkhat** [comment]
> @furkhat I had to specify OpenStack credentials manually. Is there any reason why we can't use predefined credentials?

I think I did it because explicitly setting values are simpler for design. It could be improved for UX, some other providers (aws) have options to read fields from env if it was not specified explicitly. This enhancement can be added later.

**Comment by zreigz** [comment]
\lgtm
\approve

**Pull request merged**
