### PR TITLE
Update openstack resources

### LINKED ISSUE #36: Openstack Spec Updates
@zreigz @kron4eg
How actively is this repo managed? `terraform-provider-kubermatic` is really a cool project and it seems that things got stuck in recent months even though the repo is not that old.

Is this still under active development? I would be very interested to use Terraform more frequently because REST API doesn't scale that much. I would like to do a PR but I just saw that the models you use are pretty outdated: https://github.com/kubermatic/terraform-provider-kubermatic/blob/f51d29d82a275776c84881e7694cda62c757c234/go.mod#L18

Can you give me some insights?

### PR DESCRIPTION
**Pull request by Happy2C0de**
This PR updates the relevant resources (cluster, nodedeployment, ssh_key) and adds data sources for these elements.

- I added required options that have been lately been added to the KKP, i.e. `instance_ready_check_period`, opa, mla, octavia
- I added data sources for cluster, project, sshkey, nodedeployment and the most relevant the kubeconfig. These elements were completely missing from v0.1.0
- I added the relevant tests for the added resources and work with this provider for weeks. So far, I didn't run into any crashes. For basic usage, this version is far more stable than the current provider.
- Update of a cluster and node deployment works by changing the kubernetes version setting.
- I changed the ID definition of Terraform because encoding datacenter and project and cluster ID in a Terraform ID is wrong. Now, the IDs TF uses internally are more clear and not encoded. i.e. cluster_id = cluster_id that TF uses to identify a resource.
- Added support for Flatcar image
- Several bug fixes that led to critical TF errors

Fixes #36 

This PR is an initial step into the right direction to keep the Terraform repo useful. KKP is cool but without proper usage of its API, it's almost not usable in an automated way. Terraform provider is critical such that Kubernetes clusters can be integrated into InfrastructureAsCode deployments.

I would like to see this PR merged and that a new version is released, i.e. `0.2.0`

Can you please review this PR such that users can use an upstream supported Kubermatic TF provider. 
Thanks in advance!

### CODE REVIEW

**Comment by Happy2C0de** [comment]
/assign @kron4eg @zreigz 
Have a look at this PR.
I think this is a huge step forward in the `terraform-provider-kubermatic` repo. I am looking forward to your feedback.
Totally in the spirit of the open-source community, I'd like to share the changes with Upstream such that everybody can support of my improvements. 👍

**Comment by zreigz** [comment]
@Happy2C0de thanks a lot for this PR. I have to switch my context to review and test this PR. I will try to do this tomorrow

**Comment by Happy2C0de** [comment]
> @Happy2C0de thanks a lot for this PR. I have to switch my context to review and test this PR. I will try to do this tomorrow

Thanks that you will have a look at this PR @zreigz 
Sure, come back to me when I can support you with this. Furthermore, I added a section to the `CONTRIBUTING.md` because it is not very well explained in TF documentation how one can locally build and use a provider.

**Comment by zreigz** [comment]
@Happy2C0de thanks a lot for this PR. I've tested it. Looks good
/lgtm
/approve

**Comment by judge-red** [comment]
@zreigz Thanks for merging this PR! Do you think we could get a new release?

**Comment by zreigz** [comment]
@judge-red yes :+1:

**Pull request merged**
